"""ops.source_presence — which source records still exist.

Revision ID: 0006
Revises: 0005
Created: week 2

FR-A08 asks the nightly reconcile to detect records deleted at source. `raw` is
append-only by grant, so that fact cannot be written there — and it is not a
payload the source sent, it is an observation about a pull. It belongs in `ops`,
beside the sync audit.

A vanished record keeps every raw version it ever had. Nothing is erased; it
stops being present, and the week-3 transform soft-deletes from `core` on that
basis.

Written by hand rather than autogenerated: `--autogenerate` proposes dropping
the enum check constraints that `_enum_column` creates, which it cannot see in
the model metadata. Only the new table belongs in this revision.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SOURCES = ("crm", "hris", "linkedin")
ENTITIES = (
    "program",
    "session",
    "enrollment",
    "attendance",
    "evaluation",
    "employee",
    "course_completion",
)


def upgrade() -> None:
    op.create_table(
        "source_presence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "source", sa.Enum(*SOURCES, name="sync_source", create_type=False), nullable=False
        ),
        sa.Column(
            "entity", sa.Enum(*ENTITIES, name="sync_entity", create_type=False), nullable=False
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_run_id", sa.BigInteger(), nullable=True),
        sa.Column("is_present", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("vanished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "entity", "source_id", name="uq_source_presence"),
        sa.CheckConstraint(
            "is_present = (vanished_at IS NULL)",
            name="ck_source_presence_absent_has_a_time",
        ),
        sa.CheckConstraint(
            "last_seen_at >= first_seen_at",
            name="ck_source_presence_seen_order",
        ),
        schema="ops",
        comment="Whether a source record still exists, and when it was last seen (FR-A08).",
    )
    op.create_index(
        "ix_source_presence_current",
        "source_presence",
        ["source", "entity", "is_present"],
        schema="ops",
    )
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ops TO lnd_app")


def downgrade() -> None:
    op.drop_index("ix_source_presence_current", table_name="source_presence", schema="ops")
    op.drop_table("source_presence", schema="ops")
