"""core.dim_date, core.dim_employee and app.quarantine.

Revision ID: 0007
Revises: 0006
Created: week 3

The first tables in `core` and `app`. Both schemas have existed since 0001 with
nothing in them; this is the transform layer arriving.

`dim_employee` is SCD Type 2 because the CRM has none. The source answers "who
works here now" and keeps no history, so a department move erases the previous
value the moment it happens. Every version this table holds is one that was
observed and would otherwise have been lost — and at 1,427 active employees the
cost of keeping it is nothing.

`app.quarantine` arrives in the same revision because the transform cannot be
written honestly without it. A row that cannot be keyed does not enter `core`
and is not dropped; it lands here with its reason, and the run asserts
`received = counted + quarantined` before commit. Without somewhere to put a
rejected row, that invariant has no second term and the only options are a
silent drop or a failed run.

Written by hand rather than autogenerated: `--autogenerate` proposes dropping
the enum check constraints `_enum_column` creates, which it cannot see in the
model metadata.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SOURCES = ("crm", "hris", "linkedin")
ENTITIES = (
    "program",
    "session",
    "enrollment",
    "attendance",
    "evaluation",
    "employee",
    "course_completion",
)
QUARANTINE_REASONS = (
    "unknown_employee",
    "unknown_parent",
    "unmapped_category",
    "missing_required",
    "invalid_value",
    "duplicate",
)


def upgrade() -> None:
    # ---------------------------------------------------------- core.dim_date
    op.create_table(
        "dim_date",
        sa.Column("date_key", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("quarter", sa.SmallInteger(), nullable=False),
        sa.Column("month", sa.SmallInteger(), nullable=False),
        sa.Column("day_of_month", sa.SmallInteger(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("week_of_year", sa.SmallInteger(), nullable=False),
        sa.Column("month_name", sa.String(length=16), nullable=False),
        sa.Column("month_abbr", sa.String(length=4), nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("fiscal_year", sa.SmallInteger(), nullable=False),
        sa.Column("fiscal_quarter", sa.SmallInteger(), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("date_key"),
        sa.UniqueConstraint("day"),
        sa.CheckConstraint(
            "date_key = to_char(day, 'YYYYMMDD')::int", name="ck_dim_date_key_matches"
        ),
        sa.CheckConstraint("quarter BETWEEN 1 AND 4", name="ck_dim_date_quarter"),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name="ck_dim_date_month"),
        schema="core",
        comment="One row per calendar day, with the fiscal attributes every report groups by.",
    )

    # ------------------------------------------------------ core.dim_employee
    op.create_table(
        "dim_employee",
        sa.Column("employee_key", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("employee_code", sa.String(length=64), nullable=False),
        sa.Column("odoo_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("mobile", sa.String(length=64), nullable=True),
        sa.Column("department_name", sa.Text(), nullable=True),
        sa.Column("department_odoo_id", sa.BigInteger(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("company_odoo_id", sa.BigInteger(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("position_name", sa.Text(), nullable=True),
        sa.Column("job_level_name", sa.Text(), nullable=True),
        sa.Column("job_level_grade", sa.SmallInteger(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_estimated", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("employee_key"),
        sa.UniqueConstraint("employee_code", "valid_from", name="uq_dim_employee_code_from"),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_dim_employee_period_ordered"
        ),
        sa.CheckConstraint(
            "(is_current AND valid_to IS NULL) OR (NOT is_current AND valid_to IS NOT NULL)",
            name="ck_dim_employee_current_is_open",
        ),
        sa.CheckConstraint(
            "job_level_grade IS NULL OR job_level_grade > 0",
            name="ck_dim_employee_grade_positive",
        ),
        schema="core",
        comment="The workforce as SCD Type 2. The CRM keeps no history; this is where it lives.",
    )
    # Exactly one open version per person. Across rows, so it cannot be a check
    # constraint: two current rows for one employee_code would double every
    # count that joins them and nothing downstream could detect it.
    op.create_index(
        "uq_dim_employee_one_current",
        "dim_employee",
        ["employee_code"],
        unique=True,
        postgresql_where=sa.text("is_current"),
        schema="core",
    )
    op.create_index(
        "ix_dim_employee_asof",
        "dim_employee",
        ["valid_from", "valid_to", "company_name"],
        schema="core",
    )

    # -------------------------------------------------------- app.quarantine
    op.create_table(
        "quarantine",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "source",
            sa.Enum(*SOURCES, name="quarantine_source", create_constraint=True, native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "entity",
            sa.Enum(*ENTITIES, name="quarantine_entity", create_constraint=True, native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Enum(
                *QUARANTINE_REASONS,
                name="quarantine_reason",
                create_constraint=True,
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("payload", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("sync_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_resolved", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
        comment="Rows the transform refused, with the reason. The second term of the invariant.",
    )
    op.create_index(
        "ix_quarantine_open",
        "quarantine",
        ["source", "entity", "reason"],
        postgresql_where=sa.text("NOT is_resolved"),
        schema="app",
    )

    # 0001 grants table privileges on these schemas but sequences are created
    # with their tables, so each revision that adds one has to grant it.
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core TO lnd_app")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO lnd_app")


def downgrade() -> None:
    op.drop_index("ix_quarantine_open", table_name="quarantine", schema="app")
    op.drop_table("quarantine", schema="app")
    op.drop_index("ix_dim_employee_asof", table_name="dim_employee", schema="core")
    op.drop_index("uq_dim_employee_one_current", table_name="dim_employee", schema="core")
    op.drop_table("dim_employee", schema="core")
    op.drop_table("dim_date", schema="core")
