"""Whether a report was actually sent, and to whom.

Revision ID: 0013
Revises: 0012
Created: week 9

Week 9 makes the monthly report send itself. The obvious thing to record is
that a job ran; the useful thing to record is that a **file reached people**,
which is a fact about the edition rather than about the run.

So delivery lands on `ops.export_edition`. Three columns, and the last two are
the ones that will be read a year from now:

`delivered_at`  null on an edition somebody generated by hand, because that one
                was downloaded, not sent. A trail that stamped every generation
                as a delivery would claim sends nobody made.

`delivered_to`  the addresses as they were resolved at send time. The
                distribution list changes; "who got the March report" cannot be
                answered from today's list, and this is the only place the
                answer survives.

`delivery_error` present exactly when a send was attempted and failed, or was
                skipped for want of a host or a recipient. Never a bare
                "failed": "SMTPAuthenticationError" and "timed out" send an
                operator to different places, and the console shows this string
                rather than a log nobody will open.

Nullable with no default and no backfill. The two editions already in the table
were generated by hand during week 8 and were never sent, which is exactly what
three nulls say.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OPS = "ops"


def upgrade() -> None:
    op.add_column(
        "export_edition",
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        schema=OPS,
    )
    op.add_column("export_edition", sa.Column("delivered_to", sa.Text(), nullable=True), schema=OPS)
    op.add_column(
        "export_edition", sa.Column("delivery_error", sa.Text(), nullable=True), schema=OPS
    )
    # The console's first question is "what has not gone out", and the answer
    # is a scan of undelivered rows. Partial, because a delivered edition is
    # never the subject of that query.
    op.create_index(
        "ix_export_edition_undelivered",
        "export_edition",
        ["kind", "period_year", "period_month"],
        schema=OPS,
        postgresql_where=sa.text("delivered_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_export_edition_undelivered", table_name="export_edition", schema=OPS)
    op.drop_column("export_edition", "delivery_error", schema=OPS)
    op.drop_column("export_edition", "delivered_to", schema=OPS)
    op.drop_column("export_edition", "delivered_at", schema=OPS)
