"""The shape of ops.sync_run, checked without a database.

These are deliberately assertions about the *design* rather than about
SQLAlchemy. Each one guards a decision that would fail silently if someone
undid it: renaming an enum member changes what is stored in every historical
row, and widening the active-run index from (source, entity) to (source) would
serialise five CRM entities behind one another with no error anywhere.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from lnd.db import SCHEMA_OPS
from lnd.models import (
    SyncEntity,
    SyncMode,
    SyncRun,
    SyncSource,
    SyncStatus,
    SyncTrigger,
)


class TestEnumValues:
    """The stored strings are part of the schema, not an implementation detail.

    They are written literally into migration 0002's CHECK constraints, so a
    member renamed here without a migration makes every insert fail — or worse,
    makes a new row disagree with the six months of history above it.
    """

    def test_sources(self) -> None:
        assert [s.value for s in SyncSource] == ["crm", "forms", "hris", "linkedin"]

    def test_entities(self) -> None:
        assert [e.value for e in SyncEntity] == [
            "program",
            "session",
            "enrollment",
            "attendance",
            "feedback",
            "employee",
            "course_activity",
        ]

    def test_modes(self) -> None:
        assert [m.value for m in SyncMode] == ["incremental", "full_reconcile", "backfill"]

    def test_statuses(self) -> None:
        assert [s.value for s in SyncStatus] == ["running", "success", "failed", "skipped"]

    def test_triggers(self) -> None:
        assert [t.value for t in SyncTrigger] == ["scheduled", "manual"]

    def test_str_enums_compare_as_their_value(self) -> None:
        """StrEnum, so a member is usable anywhere the wire string is."""
        assert SyncSource.CRM == "crm"
        assert f"{SyncStatus.SUCCESS}" == "success"


class TestTablePlacement:
    def test_lives_in_ops(self) -> None:
        """Operational furniture, not warehouse data."""
        assert SyncRun.__table__.schema == SCHEMA_OPS
        assert SyncRun.__tablename__ == "sync_run"

    def test_registered_on_metadata(self) -> None:
        """What alembic/env.py reads. An unregistered model looks deleted."""
        from lnd.db import Base

        assert "ops.sync_run" in Base.metadata.tables


class TestWatermarkGrain:
    """The grain is (source, entity). This is the decision most worth pinning."""

    def test_active_run_index_is_per_source_and_entity(self) -> None:
        index = next(i for i in SyncRun.__table__.indexes if i.name == "uq_sync_run_one_active")
        assert [c.name for c in index.columns] == ["source", "entity"]
        assert index.unique is True

    def test_active_run_index_is_partial_on_running(self) -> None:
        """Unique only among running rows — the whole point.

        Without the predicate this would allow one sync per entity ever.
        """
        index = next(i for i in SyncRun.__table__.indexes if i.name == "uq_sync_run_one_active")
        where = str(index.dialect_kwargs["postgresql_where"])
        assert where == "status = 'running'"

    def test_last_success_index_supports_the_freshness_query(self) -> None:
        index = next(i for i in SyncRun.__table__.indexes if i.name == "ix_sync_run_last_success")
        assert [c.name for c in index.columns] == ["source", "entity", "finished_at"]
        assert index.unique is False
        assert str(index.dialect_kwargs["postgresql_where"]) == "status = 'success'"


class TestConstraints:
    def test_every_intended_check_is_declared(self) -> None:
        """Named so a violation in the logs says which rule was broken."""
        names = {c.name for c in SyncRun.__table__.constraints if c.name}
        assert {
            "ck_sync_run_finished_after_started",
            "ck_sync_run_terminal_is_finished",
            "ck_sync_run_counts_non_negative",
            "ck_sync_run_attempts_positive",
            # Generated by the non-native enums.
            "sync_source",
            "sync_entity",
            "sync_mode",
            "sync_status",
            "sync_trigger",
        } <= names

    def test_enum_columns_are_varchar_not_native_enum(self) -> None:
        """A CHECK is swappable in a migration; ALTER TYPE fights the transaction."""
        source = SyncRun.__table__.c.source
        assert source.type.native_enum is False
        assert source.type.length == 32

    def test_identity_columns_are_required(self) -> None:
        table = SyncRun.__table__
        for column in ("source", "entity", "mode", "triggered_by", "status", "started_at"):
            assert table.c[column].nullable is False, column

    def test_outcome_columns_are_optional(self) -> None:
        """Null while running, or where the mode has no such notion.

        A full reconcile covers no window, so it has no watermark bounds.
        """
        table = SyncRun.__table__
        for column in ("finished_at", "watermark_from", "watermark_to", "error_message", "details"):
            assert table.c[column].nullable is True, column

    def test_counters_default_to_zero_in_the_database(self) -> None:
        """A server default, so a row inserted by hand in psql still counts."""
        table = SyncRun.__table__
        for column in ("records_fetched", "records_written", "records_deleted"):
            assert table.c[column].server_default is not None, column


class TestDerivedProperties:
    def test_duration_is_none_while_running(self) -> None:
        run = SyncRun(
            source=SyncSource.CRM,
            entity=SyncEntity.PROGRAM,
            mode=SyncMode.INCREMENTAL,
            status=SyncStatus.RUNNING,
            started_at=datetime.now(UTC),
        )
        assert run.duration_seconds is None
        assert run.is_finished is False

    def test_duration_is_wall_time_once_finished(self) -> None:
        started = datetime.now(UTC)
        run = SyncRun(
            source=SyncSource.HRIS,
            entity=SyncEntity.EMPLOYEE,
            mode=SyncMode.FULL_RECONCILE,
            status=SyncStatus.SUCCESS,
            started_at=started,
            finished_at=started + timedelta(seconds=92.5),
        )
        assert run.duration_seconds == 92.5
        assert run.is_finished is True

    def test_skipped_counts_as_finished(self) -> None:
        """The breaker declining to call is a terminal outcome, not an in-flight one."""
        started = datetime.now(UTC)
        run = SyncRun(
            source=SyncSource.LINKEDIN,
            entity=SyncEntity.COURSE_ACTIVITY,
            mode=SyncMode.INCREMENTAL,
            status=SyncStatus.SKIPPED,
            started_at=started,
            finished_at=started,
        )
        assert run.is_finished is True
        assert run.duration_seconds == 0.0

    def test_repr_identifies_the_run(self) -> None:
        run = SyncRun(
            source=SyncSource.CRM,
            entity=SyncEntity.ATTENDANCE,
            mode=SyncMode.INCREMENTAL,
            status=SyncStatus.RUNNING,
        )
        text = repr(run)
        assert "crm" in text
        assert "attendance" in text
