/**
 * Print every accessibility violation as a compact table, and write
 * `docs/accessibility.md`.
 *
 *   npx tsx a11y/report.ts        # or: npm run a11y:report
 *
 * The suite in `accessibility.spec.ts` is the gate — it fails a build. This is
 * the evidence: what was found, on which screen, with the colours and ratios
 * spelled out so a fix can be chosen rather than guessed at. A contrast failure
 * reported as "colour-contrast on .linkish" tells nobody which of the two
 * colours to move.
 */

import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const BASE = process.env.A11Y_BASE_URL ?? 'http://localhost:8080';
const WCAG_AA = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'];

const ROUTES: [string, string][] = [
  ['Overview', '/'],
  ['Coverage', '/coverage'],
  ['Funnel', '/funnel'],
  ['Programmes', '/programs'],
  ['Trainers', '/trainers'],
  ['Learners', '/learners'],
  ['Reports', '/reports'],
  ['Exceptions', '/exceptions'],
  ['Enrichment', '/enrichment'],
];

type Finding = {
  screen: string;
  rule: string;
  impact: string;
  target: string;
  detail: string;
};

const browser = await chromium.launch();
const context = await browser.newContext();
const page = await context.newPage();

await page.goto(`${BASE}/v1/auth/login`);
await page.waitForURL((url) => !url.pathname.startsWith('/v1/auth'));

const findings: Finding[] = [];
for (const [screen, path] of ROUTES) {
  await page.goto(`${BASE}${path}`);
  await page.waitForLoadState('networkidle');
  const { violations } = await new AxeBuilder({ page }).withTags(WCAG_AA).analyze();
  for (const violation of violations) {
    for (const node of violation.nodes) {
      const data = node.any[0]?.data as
        | { fgColor?: string; bgColor?: string; contrastRatio?: number; fontSize?: string }
        | undefined;
      findings.push({
        screen,
        rule: violation.id,
        impact: violation.impact ?? 'unknown',
        target: node.target.join(' '),
        detail:
          data?.contrastRatio !== undefined
            ? `${data.fgColor} on ${data.bgColor} — ${data.contrastRatio}:1 at ${data.fontSize}`
            : violation.help,
      });
    }
  }
}
await browser.close();

// Collapsed by rule and selector: the same class failing on nine screens is one
// fix, and listing it nine times makes a short list look like a long one.
const grouped = new Map<string, Finding & { screens: Set<string> }>();
for (const finding of findings) {
  const key = `${finding.rule}|${finding.target}|${finding.detail}`;
  const existing = grouped.get(key);
  if (existing) existing.screens.add(finding.screen);
  else grouped.set(key, { ...finding, screens: new Set([finding.screen]) });
}

const rows = [...grouped.values()].sort((a, b) => a.rule.localeCompare(b.rule));
for (const row of rows) {
  console.log(
    `${row.impact.padEnd(9)} ${row.rule.padEnd(16)} ${row.target.padEnd(28)} ${row.detail}`,
  );
}
console.log(`\n${findings.length} nodes, ${rows.length} distinct, over ${ROUTES.length} screens`);

const lines = [
  '# Accessibility',
  '',
  '<!-- GENERATED by `npm run a11y:report`. Do not edit by hand. -->',
  '',
  `Scanned ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC against the running`,
  'application, WCAG 2.1 AA, every screen.',
  '',
  '## How this is checked',
  '',
  'axe-core through a real browser, not against rendered components. Colour contrast is the',
  'rule this codebase is most likely to break and it cannot be evaluated without layout and',
  'computed styles — a component test would have reported a clean pass on every failure',
  'found below.',
  '',
  '`npm run a11y` is the gate and fails on **serious** and **critical**. Moderate and minor',
  'are reported and do not fail: a suite that fails on a decorative landmark is a suite',
  'everybody learns to run with a flag.',
  '',
  rows.length ? '## Outstanding' : '## Outstanding',
  '',
];
if (rows.length) {
  lines.push('| Impact | Rule | Element | Detail | Screens |', '|---|---|---|---|---|');
  for (const row of rows) {
    lines.push(
      `| ${row.impact} | \`${row.rule}\` | \`${row.target}\` | ${row.detail} | ${[...row.screens].join(', ')} |`,
    );
  }
} else {
  lines.push(
    'Nothing. No violation of any impact on any screen — which is a stronger statement than',
    'the gate makes, and it is the state the codebase is in as of this scan.',
  );
}
lines.push(
  '',
  '## What was found and fixed',
  '',
  'The first run reported **153 distinct violations over 182 nodes**, and all but three came',
  'from one token. `--ink-3` was `#77858a`: 3.81:1 on white, 3.48 on the ground, 3.26 on',
  "surface-2, against a 4.5 floor. It is the colour of every secondary line in the",
  'application — the sample size under a figure, the note under an enrichment row, the',
  'definition text — so one wrong value in the palette was most of the report. That is the',
  'shape a design-system failure has, and it is the argument for scanning rather than',
  'reviewing screens by eye.',
  '',
  'Two `opacity` rules were the next cause. `.badge-lag` at 0.75 and `.exclusion-aside` at',
  '0.82 each produced a colour nobody chose, at 3.43:1 and 3.92:1. Opacity reads in a',
  'stylesheet as "a quieter version of this"; to a contrast checker it is a different',
  'colour, and in the first case it was applied to the one element on screen whose job is to',
  'say the data might be stale.',
  '',
  'The rest: links in a table cell distinguished from the text beside them by 2.42:1 of',
  'colour alone, now underlined; and the drill drawer\'s virtualised grid, whose rows carried',
  '`role="row"` with two positioning divs between them and any rowgroup, so a screen reader',
  'was handed cells belonging to nothing. Its scroll container was also unreachable by',
  'keyboard, which on a forty-row window is most of the data.',
  '',
  '## Beyond the routes',
  '',
  'The gate (`npm run a11y`) also opens the two places content appears without a navigation',
  '— the drill drawer and a metric definition panel — and asserts the drawer closes on',
  'Escape. A route-level scan never sees either, and would report a clean pass on a dialog',
  'nobody can leave.',
  '',
  'Not covered: screen-reader narration, which no automated rule tests. axe finds the',
  'structural and contrast failures that make narration impossible, not whether what it says',
  'is useful.',
  '',
);

const out = resolve(import.meta.dirname, '..', '..', 'docs', 'accessibility.md');
mkdirSync(resolve(out, '..'), { recursive: true });
writeFileSync(out, lines.join('\n'), 'utf-8');
console.log(`wrote ${out}`);
