"""Verify a restored database is the same platform, not just the same bytes.

    scripts/restore-rehearsal.sh        # backs up, restores, then runs this

Week 10, Person A, and the item the runbook has refused to claim since week 2.
`pg_restore` exiting zero proves a file was readable. It does not prove the
restored database still enforces what the original enforced, and the difference
between those two is the whole reason this rehearsal exists rather than a note
saying backups are configured.

WHAT IS CHECKED, AND WHY EACH

    counts    Every grain, source against restored. A dump taken while a
              transform was mid-flight would show here as one grain short.

    grants    `raw` append-only for the application role, asked of the restored
              database. Roles live in the cluster and not in the dump, so a
              restore into a fresh cluster can succeed completely and arrive
              with every grant pointing at a role that does not exist. That is
              a platform that looks identical and has quietly lost the one
              guarantee it was built on.

    figures   Every published metric, computed out of the restored database by
              the same registry the dashboard reads. Row counts can match while
              a figure moves — a sequence restored out of step, a constraint
              that did not come across — and the figures are what anybody
              actually consumes.

It writes `docs/restore-rehearsal.md` with what it found, including the timings,
because "how long does a restore take" is the question asked during the incident
and answered badly from memory.
"""

from __future__ import annotations

import argparse
import logging
import os
import time
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import create_engine, func, select, text
from sqlalchemy.orm import Session, sessionmaker

log = logging.getLogger(__name__)

REPORT = Path(__file__).resolve().parents[4] / "docs" / "restore-rehearsal.md"

APPLICATION_ROLE = "lnd_app_rw"

#: What raw's grants must be, exactly. Append, never amend.
EXPECTED_RAW_GRANTS = {
    "SELECT": True,
    "INSERT": True,
    "UPDATE": False,
    "DELETE": False,
    "TRUNCATE": False,
}


def _census(session: Session) -> dict[str, int]:
    from lnd.ingest import RawRecord
    from lnd.models.core import (
        DimEmployee,
        DimProgram,
        DimSession,
        DimTrainer,
        FactAttendance,
        FactEnrollment,
        FactEvaluation,
    )
    from lnd.models.ops import DqException, SyncRun

    def count(model: type) -> int:
        return session.scalar(select(func.count()).select_from(model)) or 0

    return {
        "raw versions": count(RawRecord),
        "programs": count(DimProgram),
        "sessions": count(DimSession),
        "trainers": count(DimTrainer),
        "employee versions": count(DimEmployee),
        "enrollments": count(FactEnrollment),
        "attendance": count(FactAttendance),
        "evaluations": count(FactEvaluation),
        "sync runs": count(SyncRun),
        "exceptions": count(DqException),
    }


def _figures(session: Session) -> dict[str, str]:
    """Every published figure, as it would be read off a screen."""
    from lnd.metrics import registry
    from lnd.reference.windows import WORKBOOK

    return {v.title: v.formatted() for v in registry.compute_all(session, WORKBOOK)}


def _raw_grants(session: Session) -> dict[str, bool]:
    from lnd.db import SCHEMA_RAW
    from lnd.ingest import RawRecord

    table = f"{SCHEMA_RAW}.{RawRecord.__tablename__}"
    return {
        privilege: bool(
            session.scalar(
                text("SELECT has_table_privilege(:role, :table, :privilege)").bindparams(
                    role=APPLICATION_ROLE, table=table, privilege=privilege
                )
            )
        )
        for privilege in EXPECTED_RAW_GRANTS
    }


def _open(url: str) -> Session:
    return sessionmaker(bind=create_engine(url, future=True))()


def render(
    *,
    dump: str,
    target: str,
    source_census: dict[str, int],
    restored_census: dict[str, int],
    source_figures: dict[str, str],
    restored_figures: dict[str, str],
    grants: dict[str, bool],
    seconds: float,
    findings: list[str],
) -> str:
    lines = [
        "# Restore rehearsal",
        "",
        "<!-- GENERATED by `scripts/restore-rehearsal.sh`. Do not edit by hand. -->",
        "",
        f"Rehearsed {datetime.now(UTC).strftime('%Y-%m-%d %H:%M')} UTC. "
        f"Dump `{dump}`, restored into `{target}`. Backup, restore and verification "
        f"together: {seconds:,.0f} seconds.",
        "",
        "## Why this document exists",
        "",
        "The plan has recorded restore-from-backup as *configured, not proven* since week "
        "2, and the runbook refused to claim otherwise. `pg_restore` exiting zero proves a "
        "file was readable; it does not prove the restored database still enforces what "
        "the original enforced. Three things are checked here, and the second is the one "
        "that would have been missed.",
        "",
        "## What the backup is",
        "",
        "One `pg_dump -Fc` per night, taken as the owning role — the application role has "
        "no UPDATE on `raw` and no CREATE anywhere, so a dump taken as `lnd_app_rw` would "
        "be missing exactly the parts that matter. Streamed to the host rather than "
        "written inside the container: a backup on the same volume as the data it protects "
        "is not a backup. Pruned at 30 days.",
        "",
        "Until week 10 the nightly dump was a comment in `compose.prod.yaml` and nothing "
        "took one. WAL archiving was configured and the base backup it recovers *from* was "
        "not — recovery that looks provisioned and has no starting point. "
        "`scripts/backup.sh` is the missing half.",
        "",
        "## 1. Every grain, source against restored",
        "",
        "| Grain | Source | Restored | |",
        "|---|---|---|---|",
    ]
    for grain, before in source_census.items():
        after = restored_census.get(grain, 0)
        mark = "✓" if before == after else "**✗**"
        lines.append(f"| {grain} | {before:,} | {after:,} | {mark} |")

    lines += [
        "",
        "## 2. Raw is still append-only",
        "",
        "Roles live in the cluster, not in the dump. A restore into a fresh cluster can "
        "succeed completely and arrive with every grant referring to a role that does not "
        "exist — a platform that looks identical and has lost the guarantee it was built "
        "on. Asked of the restored database:",
        "",
        "| Privilege | Expected | Restored | |",
        "|---|---|---|---|",
    ]
    for privilege, expected in EXPECTED_RAW_GRANTS.items():
        actual = grants.get(privilege, False)
        mark = "✓" if actual == expected else "**✗**"
        lines.append(
            f"| {privilege} | {'granted' if expected else 'refused'} | "
            f"{'granted' if actual else 'refused'} | {mark} |"
        )

    lines += [
        "",
        "## 3. Every published figure",
        "",
        "Computed out of the restored database by the same registry the dashboard reads, "
        "over the workbook's window. Row counts can match while a figure moves.",
        "",
        "| Metric | Source | Restored | |",
        "|---|---|---|---|",
    ]
    for title, source_figure in source_figures.items():
        restored_figure = restored_figures.get(title, "—")
        mark = "✓" if source_figure == restored_figure else "**✗**"
        lines.append(f"| {title} | {source_figure} | {restored_figure} | {mark} |")

    lines += ["", "## Result", ""]
    if findings:
        lines += [
            "**The rehearsal did not pass.**",
            "",
            *(f"- {finding}" for finding in findings),
            "",
        ]
    else:
        lines += [
            f"**Passed.** Every grain, every grant and every published figure survived the "
            f"round trip. Backup, restore and verification together took "
            f"{seconds:,.0f} seconds on the dev stack.",
            "",
            "Read that number as a lower bound. It is a local dump over a loopback socket "
            "against a dataset of a few thousand rows; production adds a network, a larger "
            "volume and whoever has to be woken up. The shape of the operation is what has "
            "been proven here, not its duration.",
            "",
        ]

    lines += [
        "## What is still not proven",
        "",
        "**Point-in-time recovery.** WAL archiving is configured in `compose.prod.yaml` and "
        "this rehearsal restores a base dump only. Replaying WAL forward to a chosen "
        "moment is a different procedure with a different failure mode, and claiming it "
        "works because a dump restored would be the same mistake this document was written "
        "to end.",
        "",
        "**A fresh cluster.** The restore above went into a database on a cluster that "
        "already had the roles. `scripts/restore.sh` checks for them and stops with the "
        "remedy rather than restoring a database whose access control did not survive, but "
        "the disaster case — new host, empty cluster — has not been walked end to end.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify a restored database")
    parser.add_argument("--source-url", default=os.environ.get("RESTORE_SOURCE_URL", ""))
    parser.add_argument("--dump", default=os.environ.get("RESTORE_DUMP", "(unnamed)"))
    parser.add_argument("--target", default=os.environ.get("RESTORE_TARGET", "(unnamed)"))
    # The whole rehearsal, measured by the script that ran it. This module only
    # ever sees the verification, and reporting that as how long a restore takes
    # would answer the incident question with the fastest third of the work.
    parser.add_argument(
        "--seconds", type=float, default=float(os.environ.get("RESTORE_SECONDS", 0))
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if not args.source_url:
        parser.error("--source-url (or RESTORE_SOURCE_URL) is required")

    started = time.perf_counter()

    # DATABASE_URL is the restored copy — set by the rehearsal script, so the
    # registry and every model read the restored database exactly as the running
    # application would.
    from lnd.db import session_scope

    source = _open(args.source_url)
    try:
        source_census = _census(source)
        source_figures = _figures(source)
    finally:
        source.close()

    with session_scope() as restored:
        restored_census = _census(restored)
        restored_figures = _figures(restored)
        grants = _raw_grants(restored)

    findings: list[str] = []
    for grain, before in source_census.items():
        after = restored_census.get(grain, 0)
        if before != after:
            findings.append(f"{grain}: {before:,} in the source, {after:,} restored.")
    for privilege, expected in EXPECTED_RAW_GRANTS.items():
        if grants.get(privilege, False) != expected:
            findings.append(
                f"raw {privilege} is "
                f"{'granted' if grants.get(privilege) else 'refused'} after the restore; "
                f"it must be {'granted' if expected else 'refused'}."
            )
    for title, source_figure in source_figures.items():
        restored_figure = restored_figures.get(title, "—")
        if source_figure != restored_figure:
            findings.append(f"{title}: {source_figure} in the source, {restored_figure} restored.")

    seconds = args.seconds or (time.perf_counter() - started)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(
        render(
            dump=args.dump,
            target=args.target,
            source_census=source_census,
            restored_census=restored_census,
            source_figures=source_figures,
            restored_figures=restored_figures,
            grants=grants,
            seconds=seconds,
            findings=findings,
        ),
        encoding="utf-8",
    )
    log.info("wrote %s", REPORT)

    for finding in findings:
        log.error("FINDING %s", finding)
    if not findings:
        log.info(
            "restore verified: %d grains, %d figures, raw still append-only",
            len(source_census),
            len(source_figures),
        )
    return 1 if findings else 0


if __name__ == "__main__":  # pragma: no cover - a script
    raise SystemExit(main())
